Title: Jackbox Party Pack 5
Origin: Steam
Year: 2018
Genre: Party Game
Author: Jackbox Games
Singleplayer: true
Online: true
Local: true
Drawing: |
  `         ___        `.text; [\ ]
  `        /           `.text; [\ ]
  `        \--\        `.text; [\ ]
  `        ___/        `.text; [\ ]
  `        ____        `.text; [\ ]
  `       /@@@@\       `.text; [\ ]
  `      /@@@@@@\      `.text; [\ ]
  `  __ \|@@@@@@|/ __  `.text; [\ ]
  ` /@@\  \@@@@/  /@@\ `.text; [\ ]
  `/__@@@\      /@@@__\`.text; [\ ]
  `   |@@@@\  /@@@@|   `.text; [\ ]
  `   |@@@@|  |@@@@|   `.text; [\ ]
  `    \@@@|  |@@@/    `.text; [\ ]
  `     \__|  |__/     `.text; [\ ]
