Title: Jackbox Party Pack
Origin: Steam
Year: 2014
Genre: Party Game
Author: Jackbox Games
Singleplayer: true
Online: true
Local: true
Drawing: |
  `                    `.text; [\ ]
  `                    `.text; [\ ]
  `                    `.text; [\ ]
  `                    `.text; [\ ]
  `        ____        `.text; [\ ]
  `       /@@@@\       `.text; [\ ]
  `      /@@@@@@\      `.text; [\ ]
  `  __ \|@@@@@@|/ __  `.text; [\ ]
  ` /@@\  \@@@@/  /@@\ `.text; [\ ]
  `/__@@@\      /@@@__\`.text; [\ ]
  `   |@@@@\  /@@@@|   `.text; [\ ]
  `   |@@@@|  |@@@@|   `.text; [\ ]
  `    \@@@|  |@@@/    `.text; [\ ]
  `     \__|  |__/     `.text; [\ ]
