Title: Jackbox Party Pack 10
Origin: Steam
Year: 2023
Genre: Party Game
Author: Jackbox Games
Singleplayer: true
Online: true
Local: true
Drawing: |
  `           __       `.text; [\ ]
  `       /  /  \      `.text; [\ ]
  `      /|  |  |      `.text; [\ ]
  `      _|_ \__/      `.text; [\ ]
  `        ____        `.text; [\ ]
  `       /@@@@\       `.text; [\ ]
  `      /@@@@@@\      `.text; [\ ]
  `  __ \|@@@@@@|/ __  `.text; [\ ]
  ` /@@\  \@@@@/  /@@\ `.text; [\ ]
  `/__@@@\      /@@@__\`.text; [\ ]
  `   |@@@@\  /@@@@|   `.text; [\ ]
  `   |@@@@|  |@@@@|   `.text; [\ ]
  `    \@@@|  |@@@/    `.text; [\ ]
  `     \__|  |__/     `.text; [\ ]
