Title: Jackbox Party Pack 6
Origin: Steam
Year: 2019
Genre: Party Game
Author: Jackbox Games
Singleplayer: true
Online: true
Local: true
Drawing: |
  `         __         `.text; [\ ]
  `        |  \        `.text; [\ ]
  `        |___        `.text; [\ ]
  `        |__/        `.text; [\ ]
  `        ____        `.text; [\ ]
  `       /@@@@\       `.text; [\ ]
  `      /@@@@@@\      `.text; [\ ]
  `  __ \|@@@@@@|/ __  `.text; [\ ]
  ` /@@\  \@@@@/  /@@\ `.text; [\ ]
  `/__@@@\      /@@@__\`.text; [\ ]
  `   |@@@@\  /@@@@|   `.text; [\ ]
  `   |@@@@|  |@@@@|   `.text; [\ ]
  `    \@@@|  |@@@/    `.text; [\ ]
  `     \__|  |__/     `.text; [\ ]
