Title: Jackbox Party Pack 2
Origin: Steam
Year: 2015
Genre: Party Game
Author: Jackbox Games
Singleplayer: false
Online: true
Local: true
Drawing: |
  `         __         `.text; [\ ]
  `        /  \        `.text; [\ ]
  `         __/        `.text; [\ ]
  `        /___        `.text; [\ ]
  `        ____        `.text; [\ ]
  `       /@@@@\       `.text; [\ ]
  `      /@@@@@@\      `.text; [\ ]
  `  __ \|@@@@@@|/ __  `.text; [\ ]
  ` /@@\  \@@@@/  /@@\ `.text; [\ ]
  `/__@@@\      /@@@__\`.text; [\ ]
  `   |@@@@\  /@@@@|   `.text; [\ ]
  `   |@@@@|  |@@@@|   `.text; [\ ]
  `    \@@@|  |@@@/    `.text; [\ ]
  `     \__|  |__/     `.text; [\ ]
