Title: Jackbox Mega Picker
Origin: Steam
Year: 2024
Genre: JPP Game Launcher
Author: Jackbox Games
Singleplayer: ~
Online: ~
Local: ~
Drawing: |
  `        ????        `.text; [\ ]
  `       ??  ??       `.text; [\ ]
  `          ??        `.text; [\ ]
  `         ??         `.text; [\ ]
  `        ____        `.text; [\ ]
  `       /@@@@\       `.text; [\ ]
  `      /@@@@@@\      `.text; [\ ]
  `  __ \|@@@@@@|/ __  `.text; [\ ]
  ` /@@\  \@@@@/  /@@\ `.text; [\ ]
  `/__@@@\      /@@@__\`.text; [\ ]
  `   |@@@@\  /@@@@|   `.text; [\ ]
  `   |@@@@|  |@@@@|   `.text; [\ ]
  `    \@@@|  |@@@/    `.text; [\ ]
  `     \__|  |__/     `.text; [\ ]
