Title: Portal Reloaded
Origin: Steam
Year: 2021
Genre: First Person Puzzle Game
Author: Jannis Brinkmann
Singleplayer: true
Online: true
Local: false
Drawing: |
  show "@": set text(fill: palette.green.rgb)
  `@@@@@@@@@@@@@@@@@`.text; [\ ]
  `@@             @@`.text; [\ ]
  `@@             @@`.text; [\ ]
  `@@             @@`.text; [\ ]
  `@@             @@`.text; [\ ]
  `@@             @@`.text; [\ ]
  `@@             @@`.text; [\ ]
  `@@             @@`.text; [\ ]
  `@@             @@`.text; [\ ]
  `@@             @@`.text; [\ ]
  `@@             @@`.text; [\ ]
  `@@             @@`.text; [\ ]
  `@@             @@`.text; [\ ]
  `@@@@@@@@@@@@@@@@@`.text; [\ ]
