Title: R.E.P.O.
Origin: Steam
Year: 2025
Genre: Survival Horror
Author: semiwork
Singleplayer: true
Online: true
Local: false
Drawing: |
  show ".": set text(fill: palette.surface0.rgb)
  show "#": set text(fill: palette.red.rgb)
  `       _/----------\_       `.text; [\ ]
  `     _/##############\_     `.text; [\ ]
  `   _/##/--\######/--\##\_   `.text; [\ ]
  `  /####|@.|######|@.|####\  `.text; [\ ]
  ` /#####\--/######\--/#####\ `.text; [\ ]
  `|##########################|`.text; [\ ]
  `|--------------------------|`.text; [\ ]
  `|##########################|`.text; [\ ]
  `|##########################|`.text; [\ ]
  `|##########################|`.text; [\ ]
  `|##########################|`.text; [\ ]
  `|##########################|`.text; [\ ]
  `|##########################|`.text; [\ ]

