Title: Rhythia
Origin: GitHub
Year: 2026
Genre: Rhythm
Author: Rhythia Team
Singleplayer: true
Online: false
Local: false
Drawing: |
  show "#": set text(fill: palette.red.rgb)
  show "*": set text(fill: palette.red.rgb)
  show "+": set text(fill: palette.red.rgb)
  show "=": set text(fill: palette.red.rgb)
  `             ##***++        `.text; [\ ]
  `         #####***++===      `.text; [\ ]
  `     ########*    =====     `.text; [\ ]
  `  ########         =====    `.text; [\ ]
  `######              =====   `.text; [\ ]
  `####                 =====  `.text; [\ ]
  `#####                 ===== `.text; [\ ]
  ` #####                 =====`.text; [\ ]
  `  #####                 ====`.text; [\ ]
  `   #####              ======`.text; [\ ]
  `    ###**         ========  `.text; [\ ]
  `     #**++    =========     `.text; [\ ]
  `      *+++=========         `.text; [\ ]
  `        +======             `.text; [\ ]
