Title: Undertale
Origin: Steam
Year: 2015
Genre: RPG
Author: tobyfox
Singleplayer: true
Online: false
Local: false
Drawing: |
  show "@": set text(fill: palette.red.rgb)
  `  @@@@@@@@        @@@@@@@@  `.text; [\ ]
  `@@@@@@@@@@@@@  @@@@@@@@@@@@@`.text; [\ ]
  `@@@@@@@@@@@@@  @@@@@@@@@@@@@`.text; [\ ]
  `@@@@@@@@@@@@@@@@@@@@@@@@@@@@`.text; [\ ]
  `@@@@@@@@@@@@@@@@@@@@@@@@@@@@`.text; [\ ]
  `@@@@@@@@@@@@@@@@@@@@@@@@@@@@`.text; [\ ]
  `@@@@@@@@@@@@@@@@@@@@@@@@@@@@`.text; [\ ]
  `@@@@@@@@@@@@@@@@@@@@@@@@@@@@`.text; [\ ]
  `@@@@@@@@@@@@@@@@@@@@@@@@@@@@`.text; [\ ]
  `   @@@@@@@@@@@@@@@@@@@@@@   `.text; [\ ]
  `   @@@@@@@@@@@@@@@@@@@@@@   `.text; [\ ]
  `      @@@@@@@@@@@@@@@@      `.text; [\ ]
  `       @@@@@@@@@@@@@@@      `.text; [\ ]
  `          @@@@@@@@          `.text; [\ ]
