Title: Youtube
Origin: Web
Year: 2005
Genre: Video Sharing Site
Author: Alphapet Inc.
Singleplayer: ~
Online: ~
Local: ~
Drawing: |
  show "@": set text(fill: palette.red.rgb)
  `    @@@@@@@@@@@@@@@@@@@@    `.text; [\ ]
  `  @@@@@@@@@@@@@@@@@@@@@@@@  `.text; [\ ]
  `@@@@@@@>>>>>@@@@@@@@@@@@@@@@`.text; [\ ]
  `@@@@@@@>>>>>>>>>@@@@@@@@@@@@`.text; [\ ]
  `@@@@@@@>>>>>>>>>>>>@@@@@@@@@`.text; [\ ]
  `@@@@@@@>>>>>>>>>>>>>>@@@@@@@`.text; [\ ]
  `@@@@@@@>>>>>>>>>>>>@@@@@@@@@`.text; [\ ]
  `@@@@@@@>>>>>>>>@@@@@@@@@@@@@`.text; [\ ]
  `@@@@@@@>>>>>@@@@@@@@@@@@@@@@`.text; [\ ]
  `  @@@@@@@@@@@@@@@@@@@@@@@@  `.text; [\ ]
  `    @@@@@@@@@@@@@@@@@@@@    `.text; [\ ]
